import './globals.css';
import { AuthProvider } from "../context/AuthContext";
import { SnackbarProvider } from '../context/SnackbarContext';
import { DashboardProvider } from '../context/DashboardContext';
import { SpinnerProvider } from '../context/SpinnerContext';
import Spinner from './components/utils/Spinner';

export const metadata = {
  title: 'MissilBets',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SnackbarProvider>
          <SpinnerProvider>
            <AuthProvider>
              <DashboardProvider>
                <Spinner />
                {children}
              </DashboardProvider>
            </AuthProvider>
          </SpinnerProvider>
        </SnackbarProvider>
      </body>
    </html>
  )
}
